# Generated by Django 5.2.12 on 2026-03-24 09:36

import collections
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields
import openwisp_controller.connection.commands
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0009_alter_deviceconnection_unique_together"),
        ("openwisp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MassCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("all", "All devices"),
                            ("organization", "Organization"),
                            ("group", "Device Group"),
                            ("location", "Location"),
                            ("specific", "Specific Devices"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=openwisp_controller.connection.commands.get_command_choices,
                        max_length=16,
                    ),
                ),
                (
                    "input",
                    jsonfield.fields.JSONField(
                        blank=True,
                        dump_kwargs={"indent": 4},
                        load_kwargs={"object_pairs_hook": collections.OrderedDict},
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("in-progress", "In progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=12,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="openwisp_users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mass Command",
                "verbose_name_plural": "Mass Commands",
                "ordering": ("-created",),
                "abstract": False,
                "swappable": "CONNECTION_MASSCOMMAND_MODEL",
            },
        ),
        migrations.AddField(
            model_name="command",
            name="mass_command",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commands",
                to=settings.CONNECTION_MASSCOMMAND_MODEL,
            ),
        ),
    ]
